package br.com.cpa.questionario.model;

public enum Permissao {
    GERENCIAR_INSTITUICOES,
    GERENCIAR_USUARIOS,
    GERENCIAR_TURMAS_CURSOS,
    CRIAR_QUESTIONARIO,
    EDITAR_QUESTIONARIO,
    PUBLICAR_AVALIACAO,
    ENCERRAR_AVALIACAO,
    VISUALIZAR_RESULTADOS,
    EXPORTAR_RELATORIOS,
    GERENCIAR_PLANOS_ACAO,
    RESPONDER_AVALIACAO
}
